#!/usr/bin/env python3
"""
Macro construction certificate tool for S-pentacube a×b×z tilings.

Given a cross-section (a,b), a set of verified macro return cycles, and a
target thickness z, decomposes z into cycle lengths and constructs the
concrete S-pentacube placement list.

The construction is based on verified macro cycles through state 0 in the
complete a×b macro graph. Each cycle has a concrete placement realization
that fills exactly its thickness. Because all cycles begin and end at the
empty frontier (state 0), arbitrary concatenations of cycles produce valid
physical tilings of the combined thickness.

Usage (generalized):
    python3 tools/frontier/macro_construction.py --cross-section 5 8 \
        --cycles data/frontier/s_piece/5x8_cycles.json --thickness 100
    python3 tools/frontier/macro_construction.py --cross-section 5 6 \
        --thickness 44 --validate

Usage (backwards compatible, 5×6 default):
    python3 tools/frontier/macro_construction.py 44
    python3 tools/frontier/macro_construction.py 45 --validate
    python3 tools/frontier/macro_construction.py 100 --json

Cycle data format (JSON):
{
  "cross_section": {"a": 5, "b": 6},
  "provenance": {...},
  "cycles": {
    "4": {
      "length": 4,
      "path": [0, s1, s2, s3, 0],
      "edges": [
        {
          "source_state": 0,
          "target_state": s1,
          "template_count": 10,
          "concrete_placements": [[[x,y,z_rel], ...], ...],
          "is_pure_shift": false
        },
        ...
      ]
    },
    ...
  }
}

Generator lengths are derived from the cycle keys, not specified twice.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ==========================================================================
# Defaults (backwards compatibility with 5×6)
# ==========================================================================

_DEFAULT_CROSS_SECTION = (5, 6)
_DEFAULT_CYCLE_PATH = Path(__file__).resolve().parent / "_5x6_concrete_cycles.json"


# ==========================================================================
# Cycle data loading
# ==========================================================================

def load_cycle_data(path: Optional[Path] = None) -> dict:
    """Load concrete cycle data from a JSON file.
    
    Supports both the new generalized format (with "cross_section" and
    "cycles" keys) and the legacy flat format (cycle length -> cycle dict).
    
    Returns a dict with keys:
        cross_section: (a, b)
        cycles: {length_str: cycle_dict}
        provenance: dict (may be empty)
    """
    path = Path(path) if path else _DEFAULT_CYCLE_PATH
    
    if not path.exists():
        raise RuntimeError(
            f"Concrete cycle data not found at {path}. "
            f"Run 'python3 tools/frontier/macro_construction.py --rebuild' "
            f"to generate it."
        )
    
    with open(path) as f:
        raw = json.load(f)
    
    # Detect format
    if "cycles" in raw:
        # New generalized format
        cs = raw.get("cross_section", {})
        a = cs.get("a", _DEFAULT_CROSS_SECTION[0])
        b = cs.get("b", _DEFAULT_CROSS_SECTION[1])
        cycles = raw["cycles"]
        provenance = raw.get("provenance", {})
    else:
        # Legacy flat format: {length_str: cycle_dict}
        a, b = _DEFAULT_CROSS_SECTION
        cycles = raw
        provenance = {}
    
    return {
        "cross_section": (a, b),
        "cycles": cycles,
        "provenance": provenance,
    }


def get_generators(cycle_data: dict) -> List[int]:
    """Derive generator lengths from cycle data."""
    return sorted(int(k) for k in cycle_data["cycles"].keys())


# ==========================================================================
# Semigroup decomposition
# ==========================================================================

def decompose_thickness(z: int, generators: List[int]) -> Optional[Dict[int, int]]:
    """Decompose z into cycle length counts.
    
    Returns dict mapping cycle_length -> count, or None if z is not
    representable in the semigroup generated by `generators`.
    """
    generators = sorted(set(generators))
    
    if z < 0:
        return None
    
    # Greedy from largest
    remaining = z
    counts = {}
    for g in reversed(generators):
        counts[g] = remaining // g
        remaining = remaining % g
    
    if remaining == 0:
        return {g: c for g, c in counts.items() if c > 0}
    
    # Greedy failed; try DP
    return _decompose_dp(z, generators)


def _decompose_dp(z: int, generators: List[int]) -> Optional[Dict[int, int]]:
    """DP decomposition of z into generators."""
    generators = sorted(set(generators))
    
    # DP: representable[n] = True if n in semigroup
    max_check = z
    representable = [False] * (max_check + 1)
    representable[0] = True
    for n in range(1, max_check + 1):
        for g in generators:
            if n >= g and representable[n - g]:
                representable[n] = True
                break
    
    if not representable[z]:
        return None
    
    # Backtrack to find a decomposition
    remaining = z
    counts = {}
    while remaining > 0:
        found = False
        for g in generators:
            if remaining >= g and representable[remaining - g]:
                counts[g] = counts.get(g, 0) + 1
                remaining -= g
                found = True
                break
        if not found:
            return None
    
    return {g: c for g, c in counts.items() if c > 0}


def is_representable(z: int, generators: List[int]) -> bool:
    """Check if z is representable in the semigroup."""
    return decompose_thickness(z, generators) is not None


# ==========================================================================
# Concrete placement construction
# ==========================================================================

def construct_tiling(
    z: int,
    cycle_data: Optional[dict] = None,
    cycle_path: Optional[Path] = None,
    generators: Optional[List[int]] = None,
    preferred_cycle: Optional[int] = None,
) -> List[Tuple[Tuple[int, int, int], ...]]:
    """Construct concrete S-pentacube placements for a×b×z.
    
    Args:
        z: Target thickness (must be representable in the semigroup)
        cycle_data: Pre-loaded cycle data dict (from load_cycle_data).
                    If None, loaded from cycle_path (or default 5×6 file).
        cycle_path: Path to cycle data JSON (used if cycle_data is None)
        generators: Optional explicit generator list. If None, derived
                    from cycle data.
        preferred_cycle: Optional cycle length to prefer for decomposition.
    
    Returns:
        List of placements, each a sorted tuple of (x, y, z) cells.
    
    Raises:
        ValueError: If z is not representable.
    """
    if cycle_data is None:
        cycle_data = load_cycle_data(cycle_path)
    
    if generators is None:
        generators = get_generators(cycle_data)
    
    a, b = cycle_data["cross_section"]
    
    # Decompose z
    if preferred_cycle is not None:
        # Decompose using preferred cycle as much as possible
        counts = {}
        remaining = z
        if preferred_cycle in generators:
            counts[preferred_cycle] = remaining // preferred_cycle
            remaining = remaining % preferred_cycle
            other_gens = [g for g in generators if g != preferred_cycle]
            other = decompose_thickness(remaining, other_gens) if other_gens else None
            if other is None:
                raise ValueError(
                    f"z={z} not decomposable with preferred cycle {preferred_cycle}"
                )
            counts.update(other)
            counts = {g: c for g, c in counts.items() if c > 0}
        else:
            counts = decompose_thickness(z, generators)
    else:
        counts = decompose_thickness(z, generators)
    
    if counts is None:
        gens_str = ", ".join(map(str, generators))
        raise ValueError(
            f"z={z} is not representable in semigroup <{gens_str}>. "
            f"Frobenius number may bound the nonrepresentable range."
        )
    
    cycles = cycle_data["cycles"]
    
    all_placements: List[Tuple[Tuple[int, int, int], ...]] = []
    current_layer = 0
    
    for length, count in sorted(counts.items()):
        cycle_key = str(length)
        if cycle_key not in cycles:
            raise RuntimeError(
                f"Cycle data for length {length} not found. "
                f"Available cycles: {sorted(cycles.keys())}"
            )
        
        cycle = cycles[cycle_key]
        edges = cycle["edges"]
        
        for _rep in range(count):
            for edge in edges:
                for placement in edge["concrete_placements"]:
                    # placement contains (x, y, z_rel) with z_rel within the edge
                    abs_cells = tuple(
                        sorted((x, y, current_layer + z_rel) for (x, y, z_rel) in placement)
                    )
                    all_placements.append(abs_cells)
                
                # Every edge advances exactly 1 layer (including pure shifts)
                current_layer += 1
    
    return all_placements


# ==========================================================================
# Placement validation
# ==========================================================================

# All 24 orientations of the S pentacube (hardcoded for independence from
# the polycube_utils module)
_S_PENTACUBE_ORIENTATIONS = None


def _load_s_orientations() -> set:
    """Generate all 24 S pentacube orientations."""
    global _S_PENTACUBE_ORIENTATIONS
    if _S_PENTACUBE_ORIENTATIONS is not None:
        return _S_PENTACUBE_ORIENTATIONS
    
    import numpy as np
    
    # Canonical S piece: [[0,0,0],[1,0,0],[2,0,0],[0,0,1],[2,1,0]]
    S = np.array([[0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 0, 1], [2, 1, 0]])
    
    orientations = set()
    for sx, sy, sz in [(1,1,1),(1,1,-1),(1,-1,1),(-1,1,1),(1,-1,-1),(-1,1,-1),(-1,-1,1),(-1,-1,-1)]:
        for perm in [(0,1,2),(0,2,1),(1,0,2),(1,2,0),(2,0,1),(2,1,0)]:
            rotated = np.array([[p[perm[0]]*sx, p[perm[1]]*sy, p[perm[2]]*sz] for p in S])
            rotated -= rotated.min(axis=0)
            canonical = tuple(sorted(tuple(r) for r in rotated))
            orientations.add(canonical)
    
    _S_PENTACUBE_ORIENTATIONS = orientations
    return orientations


def validate_construction(
    placements: List[Tuple[Tuple[int, int, int], ...]],
    a: int,
    b: int,
    z: int,
) -> Dict:
    """Validate a constructed tiling independently.
    
    This validator does NOT depend on the macro search implementation.
    It only checks geometric properties.
    
    Args:
        placements: List of 5-cell placements (each as sorted tuple of cells)
        a, b, z: Box dimensions
        
    Returns:
        Dict with validation results
    """
    errors: List[str] = []
    warnings: List[str] = []
    
    expected_cells = a * b * z
    expected_pieces = expected_cells // 5 if expected_cells % 5 == 0 else 0
    
    # 1. Check piece count
    if placements:
        actual_pieces = len(placements)
        if expected_pieces and actual_pieces != expected_pieces:
            errors.append(
                f"Piece count: got {actual_pieces}, expected {expected_pieces}"
            )
    
    # 2. Check each placement
    s_orientations = _load_s_orientations()
    all_cells: set = set()
    invalid_shapes = 0
    out_of_bounds = 0
    overlaps = 0
    
    for i, placement in enumerate(placements):
        # Check length
        if len(placement) != 5:
            errors.append(f"Placement {i}: has {len(placement)} cells, expected 5")
            continue
        
        # Check bounds
        for x, y, zc in placement:
            if not (0 <= x < a and 0 <= y < b and 0 <= zc < z):
                out_of_bounds += 1
        
        # Check shape matches S pentacube
        import numpy as np
        arr = np.array(placement)
        arr -= arr.min(axis=0)
        canonical = tuple(sorted(tuple(r) for r in arr))
        if canonical not in s_orientations:
            invalid_shapes += 1
        
        # Check overlap
        for cell in placement:
            if cell in all_cells:
                overlaps += 1
            all_cells.add(cell)
    
    # 3. Check coverage
    expected_set = {(x, y, zc) for x in range(a) for y in range(b) for zc in range(z)}
    missing = expected_set - all_cells
    extra = all_cells - expected_set
    
    valid = (
        len(errors) == 0
        and invalid_shapes == 0
        and out_of_bounds == 0
        and overlaps == 0
        and len(missing) == 0
        and len(extra) == 0
        and len(all_cells) == expected_cells
    )
    
    return {
        "valid": valid,
        "a": a,
        "b": b,
        "z": z,
        "expected_cells": expected_cells,
        "expected_pieces": expected_pieces,
        "actual_pieces": len(placements),
        "actual_cells": len(all_cells),
        "errors": errors,
        "warnings": warnings,
        "invalid_shapes": invalid_shapes,
        "out_of_bounds": out_of_bounds,
        "overlaps": overlaps,
        "missing_cells": len(missing),
        "extra_cells": len(extra),
    }


# ==========================================================================
# Certificate generation
# ==========================================================================

def generate_certificate(
    z: int,
    cycle_data: Optional[dict] = None,
    cycle_path: Optional[Path] = None,
    output_path: Optional[str] = None,
) -> dict:
    """Generate a construction certificate for a×b×z.
    
    Args:
        z: Target thickness
        cycle_data: Pre-loaded cycle data (or None to load from cycle_path)
        cycle_path: Path to cycle data JSON
        output_path: If given, write certificate JSON to this path
        
    Returns:
        Certificate dict
    """
    if cycle_data is None:
        cycle_data = load_cycle_data(cycle_path)
    
    a, b = cycle_data["cross_section"]
    generators = get_generators(cycle_data)
    
    placements = construct_tiling(z, cycle_data=cycle_data)
    validation = validate_construction(placements, a=a, b=b, z=z)
    decomposition = decompose_thickness(z, generators)
    
    # Human-readable decomposition
    if decomposition:
        parts = [f"{c}×{g}" for g, c in sorted(decomposition.items(), reverse=True)]
        decomp_str = " + ".join(parts)
    else:
        decomp_str = "N/A"
    
    gens_str = ", ".join(map(str, generators))
    
    certificate = {
        "theorem": f"{a}x{b} Macro Construction",
        "cross_section": f"{a}×{b}",
        "a": a,
        "b": b,
        "thickness": z,
        "volume": a * b * z,
        "pieces": len(placements),
        "generators": generators,
        "semigroup": f"<{gens_str}>",
        "decomposition": decomp_str,
        "decomposition_counts": decomposition,
        "construction": {
            "method": "macro_cycle_concatenation",
            "cycles_used": list(set(v for v in (decomposition or {}).keys())),
            "total_repetitions": sum((decomposition or {}).values()),
            "placements_generated": len(placements),
        },
        "validation": validation,
        "provenance": cycle_data.get("provenance", {}),
    }
    
    if output_path:
        with open(output_path, "w") as f:
            json.dump(certificate, f, indent=2)
    
    return certificate


# ==========================================================================
# CLI
# ==========================================================================

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Construct S-pentacube a×b×z tilings from macro cycles"
    )
    parser.add_argument(
        "thickness",
        type=int,
        nargs="?",
        help="Target thickness z (positional, backwards-compatible)",
    )
    parser.add_argument(
        "--thickness",
        dest="thickness_opt",
        type=int,
        help="Target thickness z (keyword form)",
    )
    parser.add_argument(
        "--cross-section",
        dest="cross_section",
        type=int,
        nargs=2,
        metavar=("A", "B"),
        help="Cross-section dimensions (default: 5 6)",
    )
    parser.add_argument(
        "--cycles",
        dest="cycle_path",
        type=str,
        help="Path to concrete cycle data JSON "
             "(default: tools/frontier/_5x6_concrete_cycles.json)",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Run independent validation after construction",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output certificate as JSON",
    )
    parser.add_argument(
        "--output",
        type=str,
        help="Write certificate to file",
    )
    parser.add_argument(
        "--rebuild",
        action="store_true",
        help="Rebuild concrete cycle data from checkpoint",
    )
    parser.add_argument(
        "--semigroup",
        action="store_true",
        help="Print semigroup info and exit",
    )
    
    args = parser.parse_args()
    
    z = args.thickness if args.thickness is not None else args.thickness_opt
    
    # Load cycle data (validates the path early)
    cycle_path = Path(args.cycle_path) if args.cycle_path else None
    cycle_data = load_cycle_data(cycle_path)
    a, b = cycle_data["cross_section"]
    
    # Override cross-section if explicitly given
    if args.cross_section:
        a, b = args.cross_section
        # Note: cycle data cross-section should match; if mismatch, warn
        data_a, data_b = cycle_data["cross_section"]
        if (a, b) != (data_a, data_b):
            print(
                f"Warning: --cross-section {a}×{b} differs from cycle data "
                f"{data_a}×{data_b}. Using cycle data dimensions.",
                file=sys.stderr,
            )
            a, b = data_a, data_b
    
    generators = get_generators(cycle_data)
    
    if args.semigroup:
        print(f"Semigroup <{', '.join(map(str, generators))}>")
        print(f"  Cross-section: {a}×{b}")
        print(f"  Generators (cycle lengths): {generators}")
        return 0
    
    if args.rebuild:
        return _rebuild_concrete_cycles(a, b, cycle_path)
    
    if z is None:
        parser.print_help()
        return 1
    
    if not is_representable(z, generators):
        print(f"Error: z={z} is not representable in semigroup "
              f"<{', '.join(map(str, generators))}>", file=sys.stderr)
        return 1
    
    if args.json or args.output:
        cert = generate_certificate(
            z, cycle_data=cycle_data, output_path=args.output
        )
        if args.json:
            print(json.dumps(cert, indent=2))
    else:
        decomposition = decompose_thickness(z, generators)
        parts = [f"{c}×{g}" for g, c in sorted(decomposition.items(), reverse=True)]
        print(f"Constructing {a}×{b}×{z} tiling from macro cycles...")
        print(f"  Decomposition: {' + '.join(parts)}")
        
        placements = construct_tiling(z, cycle_data=cycle_data)
        print(f"  Generated {len(placements)} S-pentacube placements")
        
        if args.validate:
            print(f"  Running independent validation...")
            validation = validate_construction(placements, a=a, b=b, z=z)
            if validation["valid"]:
                print(f"  VALIDATION PASSED")
            else:
                print(f"  VALIDATION FAILED:")
                for err in validation["errors"]:
                    print(f"    - {err}")
                if validation["invalid_shapes"]:
                    print(f"    - {validation['invalid_shapes']} invalid shapes")
                if validation["overlaps"]:
                    print(f"    - {validation['overlaps']} overlaps")
                if validation["out_of_bounds"]:
                    print(f"    - {validation['out_of_bounds']} out-of-bounds cells")
        else:
            print(f"  Use --validate to run independent validation")
    
    return 0


def _rebuild_concrete_cycles(a: int, b: int, output_path: Optional[Path] = None) -> int:
    """Rebuild concrete cycle data from a macro checkpoint.
    
    The checkpoint must be found via environment or default path.
    For 5×6, the checkpoint is /tmp/survey_5x6_v2.ckpt.
    """
    import os
    from collections import deque
    
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
    from tools.frontier.macro_generalized import (
        load_checkpoint, build_templates_general,
        layer_mask_general, first_empty_general,
        apply_template_general, shift_state_general
    )
    
    # Checkpoint path: environment variable or 5×6 default
    checkpoint_env = os.environ.get("MACRO_CHECKPOINT")
    if checkpoint_env:
        checkpoint = Path(checkpoint_env)
    elif (a, b) == (5, 6):
        checkpoint = Path("/tmp/survey_5x6_v2.ckpt")
    else:
        print(
            f"Error: no checkpoint found for {a}×{b}. "
            f"Set MACRO_CHECKPOINT environment variable.",
            file=sys.stderr,
        )
        return 1
    
    if not checkpoint.exists():
        print(f"Error: Checkpoint not found at {checkpoint}", file=sys.stderr)
        return 1
    
    print(f"Rebuilding concrete cycle data from checkpoint {checkpoint}...")
    
    templates, NCELLS, WORD_MASK, _, _ = build_templates_general(a, b)
    ckpt = load_checkpoint(checkpoint)
    succ = ckpt["succ"]
    
    def decode_template(template):
        cells = []
        for layer in range(3):
            mask = (template >> (layer * NCELLS)) & WORD_MASK
            for cell_id in range(NCELLS):
                if mask & (1 << cell_id):
                    x = cell_id % a
                    y = cell_id // a
                    cells.append((x, y, layer))
        return cells
    
    def leads_to_target(state, target_state, visited):
        if state in visited:
            return False
        visited.add(state)
        l0 = layer_mask_general(state, 0, NCELLS)
        if l0 == WORD_MASK:
            return shift_state_general(state, NCELLS) == target_state
        target = first_empty_general(l0, NCELLS)
        for template in templates[target]:
            nxt = apply_template_general(state, template)
            if nxt is not None:
                if leads_to_target(nxt, target_state, visited):
                    return True
        return False
    
    def reconstruct_edge(source_state, target_state):
        state = source_state
        result = []
        while True:
            l0 = layer_mask_general(state, 0, NCELLS)
            if l0 == WORD_MASK:
                shifted = shift_state_general(state, NCELLS)
                if shifted == target_state:
                    return result
                return None
            target = first_empty_general(l0, NCELLS)
            found = False
            for template in templates[target]:
                nxt = apply_template_general(state, template)
                if nxt is not None:
                    if leads_to_target(nxt, target_state, set()):
                        result.append(template)
                        state = nxt
                        found = True
                        break
            if not found:
                return None
        return result
    
    # Build SCC
    reverse = {}
    for src_s, dsts in succ.items():
        for dst in dsts:
            if dst not in reverse:
                reverse[dst] = set()
            reverse[dst].add(src_s)
    
    scc0 = {0}
    q = deque([0])
    while q:
        s = q.popleft()
        if s in reverse:
            for prv in reverse[s]:
                if prv not in scc0:
                    scc0.add(prv)
                    q.append(prv)
    
    scc_succ = {}
    for s in scc0:
        scc_succ[s] = set()
    for s in succ:
        if s in scc0:
            for nxt in succ[s]:
                if nxt in scc0:
                    scc_succ[s].add(nxt)
    if 0 in succ:
        for nxt in succ[0]:
            if nxt in scc0:
                scc_succ[0].add(nxt)
    
    def extract_full_cycle(source):
        assert source in succ.get(0, set())
        q = deque()
        q.append((source, {source}, [source]))
        while q:
            state, visited, path = q.popleft()
            for nxt in sorted(scc_succ.get(state, set())):
                if nxt == 0:
                    return [0] + path + [0]
                if nxt not in visited:
                    new_visited = visited | {nxt}
                    q.append((nxt, new_visited, path + [nxt]))
        return None
    
    sources_in_scc = sorted(scc0 & ckpt["sources"])
    
    cycles = {}
    for s in sources_in_scc:
        path = extract_full_cycle(s)
        if path:
            clen = len(path) - 1
            if str(clen) not in cycles:
                edges = []
                for i in range(len(path) - 1):
                    src_s = path[i]
                    dst_s = path[i+1]
                    is_shift = (i == len(path) - 2)
                    if not is_shift:
                        tlist = reconstruct_edge(src_s, dst_s)
                    else:
                        tlist = []
                    concrete = []
                    for t in tlist:
                        cells_rel = decode_template(t)
                        concrete.append([[int(v) for v in c] for c in cells_rel])
                    edges.append({
                        "source_state": int(src_s),
                        "target_state": int(dst_s),
                        "template_count": len(tlist),
                        "concrete_placements": concrete,
                        "is_pure_shift": is_shift,
                    })
                cycles[str(clen)] = {
                    "length": clen,
                    "path": [int(s) for s in path],
                    "edges": edges,
                }
                print(f"  Cycle {clen}: {len(path)-1} edges, "
                      f"{sum(e['template_count'] for e in edges)} templates")
    
    if not cycles:
        print(f"  No cycles found in SCC(0) for {a}×{b}.")
        return 1
    
    # Write generalized format
    output = {
        "cross_section": {"a": a, "b": b},
        "provenance": {
            "checkpoint": str(checkpoint),
            "macro_graph": f"complete_{a}x{b}_macro_graph",
            "extraction_date": "2026-08-23",
        },
        "cycles": cycles,
    }
    
    out_path = output_path if output_path else (
        Path(__file__).resolve().parent / f"_{a}x{b}_concrete_cycles.json"
    )
    with open(out_path, "w") as f:
        json.dump(output, f)
    
    print(f"\nConcrete cycle data written to {out_path}")
    print(f"Cycles: {sorted(cycles.keys())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())