#!/usr/bin/env python3
"""
Numerical semigroup analysis for S-pentacube macro cycle lengths.

Computes the semigroup generated by a set of cycle lengths,
determines Frobenius number, conductor, Apéry set, and
representability table.

Usage:
    python3 tools/frontier/macro_semigroup.py [generators...]
    
    Default: 4 29 46 47 (5×6 S-pentacube cycles)
    
    python3 tools/frontier/macro_semigroup.py 4 29 46 47
    python3 tools/frontier/macro_semigroup.py 6  (4×5 cycle)
    python3 tools/frontier/macro_semigroup.py 5 10  (4×6 cycles)
    python3 tools/frontier/macro_semigroup.py 20 130  (4×8 cycles)
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import List


def compute_semigroup(
    generators: List[int],
    max_check: int = 500,
) -> dict:
    """
    Compute numerical semigroup properties.
    
    Args:
        generators: List of positive integer generators
        max_check: Upper bound for representability check
        
    Returns:
        Dictionary with semigroup properties
    """
    generators = sorted(set(generators))
    
    if not generators or generators[0] <= 0:
        raise ValueError("Generators must be positive integers")
    
    # Compute GCD of generators
    import math
    g = generators[0]
    for gen in generators[1:]:
        g = math.gcd(g, gen)
    semigroup_gcd = g
    
    # DP for representability
    representable = [False] * (max_check + 1)
    representable[0] = True
    
    for n in range(1, max_check + 1):
        for g in generators:
            if n >= g and representable[n - g]:
                representable[n] = True
                break
    
    # Nonrepresentable numbers
    nonrepresentable = [n for n in range(1, max_check + 1) if not representable[n]]
    
    # Frobenius number: only meaningful when GCD = 1
    if semigroup_gcd == 1:
        frobenius = max(nonrepresentable) if nonrepresentable else 0
    else:
        frobenius = None  # infinite gaps, no finite Frobenius number
    
    # Conductor: only meaningful when GCD = 1
    if semigroup_gcd == 1:
        conductor = 0
        for n in range(max_check + 1):
            all_rep = True
            for m in range(n, max_check + 1):
                if not representable[m]:
                    all_rep = False
                    break
            if all_rep:
                conductor = n
                break
    else:
        conductor = None  # infinite gaps, no finite conductor
    
    # Apéry set with respect to smallest generator
    min_gen = generators[0]
    apery_set = {}
    for r in range(min_gen):
        for n in range(0, max_check + 1):
            if representable[n] and n % min_gen == r:
                if n - min_gen < 0 or not representable[n - min_gen]:
                    apery_set[r] = n
                    break
    
    # Verify conductor
    if conductor is not None:
        verify_ok = all(representable[n] for n in range(conductor, max_check + 1))
    else:
        verify_ok = None  # not applicable when GCD > 1
    
    # Build representability table
    table = {}
    for n in range(0, max_check + 1):
        if representable[n]:
            # Find a representation
            remaining = n
            counts = {}
            for g in sorted(generators, reverse=True):
                counts[g] = 0
                while remaining >= g and representable[remaining - g]:
                    counts[g] += 1
                    remaining -= g
            table[n] = {
                "representable": True,
                "representation": {str(g): c for g, c in counts.items() if c > 0},
            }
        else:
            table[n] = {"representable": False, "representation": None}
    
    return {
        "generators": generators,
        "gcd": semigroup_gcd,
        "min_generator": min_gen,
        "frobenius_number": frobenius,
        "conductor": conductor,
        "apery_set": apery_set,
        "nonrepresentable_count": len(nonrepresentable),
        "nonrepresentable_below_conductor": [n for n in nonrepresentable if conductor is None or n < conductor],
        "nonrepresentable_all": nonrepresentable,
        "verification": {
            "max_check": max_check,
            "all_representable_above_conductor": verify_ok,
        },
        "representability_table": table,
    }


def print_report(result: dict) -> None:
    """Print a human-readable semigroup report."""
    gens = result["generators"]
    g = result["gcd"]
    print(f"Numerical Semigroup <{', '.join(map(str, gens))}>")
    if g > 1:
        print(f"  (GCD = {g}, not a numerical semigroup — infinite gaps)")
    print(f"{'=' * 60}")
    print()
    print(f"Minimal generator: {result['min_generator']}")
    if result["frobenius_number"] is not None:
        print(f"Frobenius number:  {result['frobenius_number']}")
    else:
        print(f"Frobenius number:  infinite (GCD > 1)")
    if result["conductor"] is not None:
        print(f"Conductor:         {result['conductor']}")
    else:
        print(f"Conductor:         infinite (GCD > 1)")
    print()
    print(f"Apéry set Ap(S, {result['min_generator']}):")
    for r, v in sorted(result["apery_set"].items()):
        print(f"  residue {r} mod {result['min_generator']}: {v}")
    print()
    
    nonrep = result["nonrepresentable_below_conductor"]
    if result["conductor"] is not None:
        print(f"Nonrepresentable below conductor ({len(nonrep)} values):")
        print(f"  {nonrep}")
        print()
        print(f"Verification: all n >= {result['conductor']} are representable: "
              f"{result['verification']['all_representable_above_conductor']}")
    else:
        print(f"Nonrepresentable (first {min(30, len(nonrep))} values):")
        print(f"  {nonrep[:30]}")
    print()
    
    # Show first few representable numbers
    print("Representability table (first 60 values):")
    print("  n  | rep | representation")
    print("  ---+-----+---------------")
    for n in range(0, 61):
        entry = result["representability_table"].get(n, {})
        if entry.get("representable"):
            rep = entry["representation"]
            rep_str = " + ".join(f"{c}*{g}" for g, c in sorted(rep.items(), key=lambda x: -int(x[0])))
            print(f"  {n:2d} | YES | {rep_str}")
        else:
            print(f"  {n:2d} | NO  |")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Numerical semigroup analysis for macro cycle lengths"
    )
    parser.add_argument(
        "generators",
        type=int,
        nargs="*",
        default=[4, 29, 46, 47],
        help="Cycle length generators (default: 4 29 46 47)",
    )
    parser.add_argument(
        "--max-check",
        type=int,
        default=500,
        help="Upper bound for representability check (default: 500)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output as JSON",
    )
    
    args = parser.parse_args()
    
    result = compute_semigroup(args.generators, max_check=args.max_check)
    
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print_report(result)
    
    return 0


if __name__ == "__main__":
    raise SystemExit(main())