#!/usr/bin/env python3
"""
Production V45 CK6 enumeration driver (corrected architecture).

This is the ONLY sanctioned way to run the production V45 enumeration.
It uses exclusively:

  - the corrected 3,696-min-id shard plan
    (data/ck6_reuse/ck6_v45_shards_corrected.json, planner
    "corrected-sound-filter", generated by
    solvers/ck6_sharding_corrected.build_corrected_plan(45, 8));
  - the connectivity-pruned engine
    (solvers/t_ck6_oddity_v35_search.iter_targets_seeded_connected),
    validated at production scale (see
    docs/frontier/v45_enumeration_validation.md);
  - the driver's own funnel + exact-cover + dual-solver audit
    (t_ck6_reuse_multipiece._process_target / funnel_and_cover),
    imported unmodified.

It NEVER reads data/ck6_v45/* (the retired 1,469,999-target corpus), never
references the historical 86-min-id shard plan, and has NO expected-total
parameter: the V45 total is UNKNOWN until this run completes, so all
conservation checks are internal (sum of shard counts == sum of per-min-id
counts).

Startup assertions (fail loudly, before any work):
  - volume == 45
  - corrected plan coverage == 3,696 candidates
  - min-id 3590 present (George's B-9 target)
  - min-ids 3652 and 3937 present (the V45 start-front orbits)
  - no duplicate min-id ownership (3,696 unique ids)
  - the plan file matches a fresh build_corrected_plan(45, 8)
  - the retired total 1,469,999 is never used as an expected result

Checkpoint / resume semantics (safe by construction):
  - shard_XXX.json is written ATOMICALLY (tmp + os.replace) ONLY when the
    shard has fully completed.  Its presence is the completion marker; a
    partial shard never looks complete.
  - shard_XXX.ckpt is written ATOMICALLY after every completed min-id
    bucket and holds the FULL worker state (funnel counters, targets,
    sat/unsat, witnesses, per-min-id counts).  A killed shard resumes
    exactly from the checkpoint; a stale/corrupt checkpoint is discarded
    and the shard restarts fresh.
  - A STOP file in the workdir makes workers exit cleanly WITHOUT a result
    file (checkpoint preserved); the orchestrator re-runs such shards on
    the next invocation.
  - The orchestrator re-launches any shard without a result file (crash
    recovery), up to --max-retries per shard.
  - final.json is written ATOMICALLY only when ALL shards have result
    files; it is never a partial aggregate.

Usage:
  python tools/frontier/run_v45_production.py --piece A            # orchestrator
  python tools/frontier/run_v45_production.py --piece A --shard 7  # one shard

Outputs (workdir data/ck6_reuse/run/v45_<PIECE>/):
  shard_XXX.json   per-shard result (completion marker)
  shard_XXX.ckpt   per-shard resume checkpoint (removed on completion)
  shard_XXX.log    worker stdout/stderr
  final.json       aggregate (only when all shards complete)
  plus one line appended to data/ck6_reuse/piece_volume_results.jsonl
"""
import argparse
import json
import os
import resource
import subprocess
import sys
import time
from collections import Counter

REPO = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "solvers"))

from t_ck6_oddity_v35_search import (  # noqa: E402
    build_universe,
    iter_targets_seeded_connected,
)
from ck6_sharding_corrected import (  # noqa: E402
    build_corrected_plan,
    corrected_candidate_min_ids,
)
from t_ck6_reuse_multipiece import (  # noqa: E402
    _append_jsonl,
    _check_t_anchor,
    _finalize,
    _new_state,
    _process_target,
    combo_workdir,
    PENTACUBES,
)
from common.fastfunnel import FastFunnel  # noqa: E402

PLAN_PATH = os.path.join(REPO, "data", "ck6_reuse",
                         "ck6_v45_shards_corrected.json")
VOLUME = 45
BUDGET = (VOLUME - 1) // 2  # 22
N_CANDIDATES = 3696
RETIRED_TOTAL = 1469999  # the buggy prefilter total; never an expectation


def startup_assertions(plan, un):
    """Hard assertions before any enumeration work (task gate)."""
    assert plan["volume"] == VOLUME, plan["volume"]
    assert plan["planner"] == "corrected-sound-filter", plan["planner"]
    assert plan["n_candidates"] == N_CANDIDATES, plan["n_candidates"]
    ids = [m for sh in plan["shards"] for m in sh["min_ids"]]
    assert len(ids) == N_CANDIDATES, len(ids)
    assert len(set(ids)) == N_CANDIDATES, "duplicate min-id ownership"
    assert 3590 in ids, "min-id 3590 (George B-9) missing from plan"
    assert 3652 in ids and 3937 in ids, "start-front min-ids missing"
    # the plan file must match a fresh build of the corrected plan
    fresh, _ = build_corrected_plan(VOLUME, 8)
    assert fresh["shards"] == plan["shards"], \
        "plan file diverges from fresh corrected plan"
    # the corrected domain must itself be the sound filter's output
    assert sorted(ids) == sorted(corrected_candidate_min_ids(un)), \
        "plan min-ids != corrected_candidate_min_ids(un)"
    # the retired total is never an expected result: this driver has no
    # expected-total parameter; conservation is internal only
    assert RETIRED_TOTAL not in ids
    print(f"  [PASS] startup assertions: volume={VOLUME} "
          f"candidates={len(ids)} unique={len(set(ids))} "
          f"3590/3652/3937 present, plan == fresh corrected plan")


def _write_atomic(path, obj):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(obj, f, default=dict, indent=1)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def run_shard(piece, shard_idx, plan, workdir, stop_path):
    """Enumerate one shard of the corrected plan with the pruned engine."""
    sh = next(s for s in plan["shards"] if s["shard"] == shard_idx)
    result_path = os.path.join(workdir, f"shard_{shard_idx:03d}.json")
    if os.path.exists(result_path):
        print(f"shard {shard_idx}: already complete (result file present)")
        return
    ckpt_path = os.path.join(workdir, f"shard_{shard_idx:03d}.ckpt")
    un = build_universe(VOLUME)
    piece_cells = [tuple(map(int, c)) for c in PENTACUBES[piece]]
    ff = FastFunnel(piece_cells, un["ball"])
    index = ff.index
    k = VOLUME // 5
    state = _new_state(VOLUME, piece, shard=shard_idx)
    state["workdir"] = workdir
    done = {}
    if os.path.exists(ckpt_path):
        try:
            with open(ckpt_path) as f:
                ck = json.load(f)
            if (ck.get("volume") == VOLUME and ck.get("piece") == piece
                    and ck.get("shard") == shard_idx):
                state = ck["state"]
                done = {int(k): v for k, v in ck["done"].items()}
                print(f"shard {shard_idx}: resumed from checkpoint "
                      f"({len(done)}/{len(sh['min_ids'])} min-ids done, "
                      f"{state['targets']:,} targets)", flush=True)
            else:
                raise ValueError("checkpoint identity mismatch")
        except Exception as e:  # stale/corrupt checkpoint -> fresh start
            print(f"shard {shard_idx}: discarding unusable checkpoint "
                  f"({e}); fresh start", flush=True)
            os.remove(ckpt_path)
            state = _new_state(VOLUME, piece, shard=shard_idx)
            state["workdir"] = workdir
            done = {}
    t0 = time.time()
    for s in sh["min_ids"]:
        if s in done:
            continue
        cnt = 0
        for t in iter_targets_seeded_connected(un, s, BUDGET):
            _process_target(t, state, index, ff, k)
            cnt += 1
            if cnt % 1_000_000 == 0:
                if os.path.exists(stop_path):
                    break
        done[s] = cnt
        state["per_min_id"] = {str(k): v for k, v in sorted(done.items())}
        _write_atomic(ckpt_path, {"volume": VOLUME, "piece": piece,
                                  "shard": shard_idx, "done": done,
                                  "state": state})
        print(f"shard {shard_idx}: min-id {s} done ({cnt:,} targets, "
              f"cumulative {state['targets']:,}, "
              f"{time.time()-t0:.0f}s)", flush=True)
        if os.path.exists(stop_path):
            print(f"shard {shard_idx}: STOP file present; exiting without "
                  f"result (checkpoint preserved)", flush=True)
            return
    state["status"] = "complete"
    state["elapsed_s"] = round(time.time() - t0, 1)
    state["peak_rss_mb"] = round(
        resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024, 1)
    _write_atomic(result_path, state)
    os.remove(ckpt_path)
    print(f"shard {shard_idx}: COMPLETE {state['targets']:,} targets "
          f"({state['elapsed_s']}s, peak {state['peak_rss_mb']} MiB)",
          flush=True)


def aggregate(piece, workdir, plan):
    """Aggregate completed shards into final.json (internal conservation)."""
    total = _new_state(VOLUME, piece)
    total["workdir"] = workdir
    missing = []
    per_min_sum = 0
    for sh in plan["shards"]:
        path = os.path.join(workdir, f"shard_{sh['shard']:03d}.json")
        if not os.path.exists(path):
            missing.append(sh["shard"])
            continue
        with open(path) as f:
            r = json.load(f)
        total["targets"] += r["targets"]
        for key, v in r["funnel"].items():
            total["funnel"][key] += v
        total["sat"] += r["sat"]
        total["unsat"] += r["unsat"]
        total["covers_total"] += r.get("covers_total", 0)
        total["covers_max"] = max(total["covers_max"],
                                  r.get("covers_max", 0))
        total["witnesses"].extend(r["witnesses"])
        total["elapsed_s"] = max(total.get("elapsed_s", 0),
                                 r.get("elapsed_s", 0))
        total["peak_rss_mb"] = max(total.get("peak_rss_mb", 0),
                                   r.get("peak_rss_mb", 0))
        per_min_sum += sum(int(v) for v in r.get("per_min_id", {}).values())
    if missing:
        return None, missing
    # internal conservation: shard totals == per-min-id totals.  There is
    # NO expected total: the V45 total is unknown until this run completes.
    assert total["targets"] == per_min_sum, \
        (total["targets"], per_min_sum)
    _check_t_anchor(VOLUME, piece, total)  # no-op for V45 (no anchor)
    final = _finalize(VOLUME, piece, total, "COMPLETE")
    _write_atomic(os.path.join(workdir, "final.json"), final)
    _append_jsonl(final)
    return final, []


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--piece", required=True,
                    choices=sorted(PENTACUBES))
    ap.add_argument("--volume", type=int, default=VOLUME)
    ap.add_argument("--shard", type=int, default=None,
                    help="run one shard only (worker mode)")
    ap.add_argument("--parallel", type=int, default=2,
                    help="parallel workers (default 2: worst-case bucket "
                         "~6.1 GB RSS x 2 fits the 28 GB host)")
    ap.add_argument("--max-retries", type=int, default=5,
                    help="orchestrator re-launch attempts per shard")
    args = ap.parse_args()

    assert args.volume == VOLUME, f"volume must be {VOLUME}"
    with open(PLAN_PATH) as f:
        plan = json.load(f)
    un = build_universe(VOLUME)
    startup_assertions(plan, un)
    workdir = combo_workdir(VOLUME, args.piece)
    os.makedirs(workdir, exist_ok=True)
    stop_path = os.path.join(workdir, "STOP")

    if args.shard is not None:
        run_shard(args.piece, args.shard, plan, workdir, stop_path)
        return

    final_path = os.path.join(workdir, "final.json")
    if os.path.exists(final_path):
        with open(final_path) as f:
            print(f"[prod] V45 {args.piece}: already complete (resume)")
        return
    pending = [s["shard"] for s in plan["shards"]
               if not os.path.exists(os.path.join(
                   workdir, f"shard_{s['shard']:03d}.json"))]
    print(f"[prod] V45 {args.piece}: {len(pending)} shards to run on "
          f"{args.parallel} workers (workdir {workdir})", flush=True)
    retries = {}
    queue = list(pending)
    running = {}
    while queue or running:
        while queue and len(running) < args.parallel:
            i = queue.pop(0)
            logf = open(os.path.join(workdir, f"shard_{i:03d}.log"), "a")
            p = subprocess.Popen(
                [sys.executable, os.path.abspath(__file__),
                 "--piece", args.piece, "--shard", str(i)],
                stdout=logf, stderr=subprocess.STDOUT)
            running[i] = p
            print(f"[prod] launched shard {i} (pid {p.pid})", flush=True)
        for i in [i for i, p in running.items() if p.poll() is not None]:
            rc = running.pop(i).returncode
            done = os.path.exists(os.path.join(
                workdir, f"shard_{i:03d}.json"))
            print(f"[prod] shard {i} finished rc={rc} "
                  f"result={'present' if done else 'absent'}", flush=True)
            if not done:
                retries[i] = retries.get(i, 0) + 1
                if retries[i] > args.max_retries:
                    raise RuntimeError(
                        f"shard {i} failed {args.max_retries} times; "
                        f"aborting (checkpoint preserved)")
                queue.append(i)  # re-launch (resumes from checkpoint)
        if os.path.exists(stop_path) and not queue:
            print("[prod] STOP file present; no shards in flight",
                  flush=True)
            break
        time.sleep(2)
    final, missing = aggregate(args.piece, workdir, plan)
    if final is None:
        print(f"[prod] incomplete: {len(missing)} shards missing "
              f"({missing}); re-run to resume", flush=True)
        return 1
    print(f"[prod] V45 {args.piece}: targets={final['number_of_targets']:,} "
          f"candidates={final['exact_cover_candidates']} "
          f"SAT={final['sat_count']} "
          f"(shard max {final['elapsed_shard_max_s']:.0f}s)", flush=True)
    print(f"[prod] final.json written to {final_path}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())