#!/usr/bin/env python3
"""
Production V45 CK6 enumeration driver (corrected architecture).

This is the ONLY sanctioned way to run the production V45 enumeration.
It uses exclusively:

  - the corrected 3,696-min-id shard plan
    (data/ck6_reuse/ck6_v45_shards_corrected.json, planner
    "corrected-sound-filter", generated by
    solvers/ck6_sharding_corrected.build_corrected_plan(45, 8));
  - the connectivity-pruned engine
    (solvers/t_ck6_oddity_v35_search.iter_targets_seeded_connected),
    validated at production scale (see
    docs/frontier/v45_enumeration_validation.md);
  - the driver's own funnel + exact-cover + dual-solver audit
    (t_ck6_reuse_multipiece._process_target / funnel_and_cover),
    imported unmodified.

The per-bucket visited set is SQLite-backed
(iter_targets_seeded_connected_sqlite): identical traversal and target
set to the in-memory engine (the visited set is only a membership
test), with bounded RSS (~1.1 GiB for the largest bucket) and crash-safe
mid-bucket resume.  See docs/frontier/v45_memory_bottleneck.md.

It NEVER reads data/ck6_v45/* (the retired 1,469,999-target corpus), never
references the historical 86-min-id shard plan, and has NO expected-total
parameter: the V45 total is UNKNOWN until this run completes, so all
conservation checks are internal (sum of shard counts == sum of per-min-id
counts).

Startup assertions (fail loudly, before any work):
  - volume == 45
  - corrected plan coverage == 3,696 candidates
  - min-id 3590 present (George's B-9 target)
  - min-ids 3652 and 3937 present (the V45 start-front orbits)
  - no duplicate min-id ownership (3,696 unique ids)
  - the plan file matches a fresh build_corrected_plan(45, 8)
  - the retired total 1,469,999 is never used as an expected result

Checkpoint / resume semantics (safe by construction):
  - shard_XXX.json is written ATOMICALLY (tmp + os.replace) ONLY when the
    shard has fully completed.  Its presence is the completion marker; a
    partial shard never looks complete.
  - shard_XXX.ckpt is written ATOMICALLY after every completed min-id
    bucket and holds the FULL worker state (funnel counters, targets,
    sat/unsat, witnesses, per-min-id counts) plus the run_id.  A killed
    shard resumes exactly from the checkpoint; a stale/corrupt checkpoint
    is discarded and the shard restarts fresh.
  - bucket_XXXX.sqlite (one per min-id bucket, in the workdir) holds the
    bucket's SQLite visited set plus a mid-bucket checkpoint (DFS stack,
    counters, pickled worker state) committed in the same transaction as
    the visited-set inserts.  A bucket killed mid-way resumes exactly from
    its database; a completed bucket keeps its database (marked complete)
    as audit evidence -- it is NEVER deleted automatically (use
    --prune-dbs to remove complete databases explicitly).
  - A STOP file in the workdir makes workers exit cleanly WITHOUT a result
    file (checkpoint preserved).  The in-flight bucket is NOT recorded as
    done: it resumes from its SQLite checkpoint on the next invocation, so
    no bucket is ever silently truncated.
  - The orchestrator re-launches any shard without a result file (crash
    recovery), up to --max-retries per shard.
  - final.json is written ATOMICALLY only when ALL shards have result
    files; it is never a partial aggregate.

Usage:
  python tools/frontier/run_v45_production.py --piece A            # orchestrator
  python tools/frontier/run_v45_production.py --piece A --shard 7  # one shard
  python tools/frontier/run_v45_production.py --piece A --prune-dbs
      # explicit cleanup: delete COMPLETE bucket databases only

Outputs (workdir data/ck6_reuse/run/v45_<PIECE>/):
  shard_XXX.json   per-shard result (completion marker)
  shard_XXX.ckpt   per-shard resume checkpoint (removed on completion)
  shard_XXX.log    worker stdout/stderr
  bucket_XXXX.sqlite  per-bucket visited set + mid-bucket checkpoint
                      (kept after completion as audit evidence)
  final.json       aggregate (only when all shards complete)
  plus one line appended to data/ck6_reuse/piece_volume_results.jsonl

Launched workers (and the orchestrator itself) are recorded in
data/ck6_reuse/openwork_jobs.jsonl so a new OpenWork session can detect
orphaned jobs from a crashed session before starting expensive work
(see tools/frontier/orphan_check.py and
docs/frontier/OPENWORK_STATUS.md).
"""
import argparse
import json
import os
import resource
import subprocess
import sys
import time
import uuid
from collections import Counter

REPO = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "solvers"))

from t_ck6_oddity_v35_search import (  # noqa: E402
    BucketRunInfo,
    BucketStopped,
    SearchLimit,
    build_universe,
    iter_targets_seeded_connected_sqlite,
)
from ck6_sharding_corrected import (  # noqa: E402
    build_corrected_plan,
    corrected_candidate_min_ids,
)
from orphan_check import register_job  # noqa: E402
from t_ck6_reuse_multipiece import (  # noqa: E402
    _append_jsonl,
    _check_t_anchor,
    _finalize,
    _new_state,
    _process_target,
    combo_workdir,
    PENTACUBES,
)
from common.fastfunnel import FastFunnel  # noqa: E402

PLAN_PATH = os.path.join(REPO, "data", "ck6_reuse",
                         "ck6_v45_shards_corrected.json")
VOLUME = 45
BUDGET = (VOLUME - 1) // 2  # 22
N_CANDIDATES = 3696
RETIRED_TOTAL = 1469999  # the buggy prefilter total; never an expectation
CKPT_EVERY = 2_000_000  # bucket DB checkpoint cadence (states)


def startup_assertions(plan, un):
    """Hard assertions before any enumeration work (task gate)."""
    assert plan["volume"] == VOLUME, plan["volume"]
    assert plan["planner"] == "corrected-sound-filter", plan["planner"]
    assert plan["n_candidates"] == N_CANDIDATES, plan["n_candidates"]
    ids = [m for sh in plan["shards"] for m in sh["min_ids"]]
    assert len(ids) == N_CANDIDATES, len(ids)
    assert len(set(ids)) == N_CANDIDATES, "duplicate min-id ownership"
    assert 3590 in ids, "min-id 3590 (George B-9) missing from plan"
    assert 3652 in ids and 3937 in ids, "start-front min-ids missing"
    # the plan file must match a fresh build of the corrected plan
    fresh, _ = build_corrected_plan(VOLUME, 8)
    assert fresh["shards"] == plan["shards"], \
        "plan file diverges from fresh corrected plan"
    # the corrected domain must itself be the sound filter's output
    assert sorted(ids) == sorted(corrected_candidate_min_ids(un)), \
        "plan min-ids != corrected_candidate_min_ids(un)"
    # the retired total is never an expected result: this driver has no
    # expected-total parameter; conservation is internal only
    assert RETIRED_TOTAL not in ids
    print(f"  [PASS] startup assertions: volume={VOLUME} "
          f"candidates={len(ids)} unique={len(set(ids))} "
          f"3590/3652/3937 present, plan == fresh corrected plan")


def _write_atomic(path, obj):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(obj, f, default=dict, indent=1)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def prune_completed_dbs(workdir):
    """Explicit cleanup: delete ONLY COMPLETE bucket databases.

    A bucket database is complete when its meta table carries
    'complete' == '1' (written in the same transaction as the final
    checkpoint).  Complete databases have no resume value left, so
    removing them loses nothing; incomplete databases hold mid-bucket
    resume state and are NEVER touched here.
    """
    import sqlite3
    removed = kept = 0
    for name in sorted(os.listdir(workdir)):
        if not (name.startswith("bucket_") and name.endswith(".sqlite")):
            continue
        path = os.path.join(workdir, name)
        try:
            con = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
            row = con.execute(
                "SELECT value FROM meta WHERE key='complete'").fetchone()
            con.close()
        except sqlite3.Error:
            kept += 1
            continue
        if row is not None and row[0] == b"1":
            os.remove(path)
            removed += 1
            print(f"[prune] removed {name}", flush=True)
        else:
            kept += 1
    print(f"[prune] removed {removed} complete DBs, kept {kept} "
          f"(incomplete/resume or unreadable)", flush=True)


def run_shard(piece, shard_idx, plan, workdir, stop_path, max_seconds=None):
    """Enumerate one shard of the corrected plan with the SQLite-backed
    pruned engine (bounded RSS, crash-safe mid-bucket resume)."""
    sh = next(s for s in plan["shards"] if s["shard"] == shard_idx)
    result_path = os.path.join(workdir, f"shard_{shard_idx:03d}.json")
    if os.path.exists(result_path):
        print(f"shard {shard_idx}: already complete (result file present)")
        return
    ckpt_path = os.path.join(workdir, f"shard_{shard_idx:03d}.ckpt")
    un = build_universe(VOLUME)
    piece_cells = [tuple(map(int, c)) for c in PENTACUBES[piece]]
    ff = FastFunnel(piece_cells, un["ball"])
    index = ff.index
    k = VOLUME // 5
    state = _new_state(VOLUME, piece, shard=shard_idx)
    state["workdir"] = workdir
    done = {}
    run_id = None
    if os.path.exists(ckpt_path):
        try:
            with open(ckpt_path) as f:
                ck = json.load(f)
            if (ck.get("volume") == VOLUME and ck.get("piece") == piece
                    and ck.get("shard") == shard_idx):
                state = ck["state"]
                # JSON round-trip turns the funnel Counter into a plain
                # dict; restore Counter so missing-key increments work
                state["funnel"] = Counter(state["funnel"])
                done = {int(k): v for k, v in ck["done"].items()}
                run_id = ck.get("run_id")
                print(f"shard {shard_idx}: resumed from checkpoint "
                      f"({len(done)}/{len(sh['min_ids'])} min-ids done, "
                      f"{state['targets']:,} targets)", flush=True)
            else:
                raise ValueError("checkpoint identity mismatch")
        except Exception as e:  # stale/corrupt checkpoint -> fresh start
            print(f"shard {shard_idx}: discarding unusable checkpoint "
                  f"({e}); fresh start", flush=True)
            os.remove(ckpt_path)
            state = _new_state(VOLUME, piece, shard=shard_idx)
            state["workdir"] = workdir
            done = {}
    if run_id is None:
        # no checkpoint (or a pre-SQLite one): start a new run identity.
        # Bucket databases from any other run_id are discarded as stale.
        run_id = uuid.uuid4().hex
        print(f"shard {shard_idx}: new run_id {run_id}", flush=True)
    limits = None
    if max_seconds is not None:
        limits = {"max_seconds": max_seconds, "t0": time.time()}
    t0 = time.time()
    for s in sh["min_ids"]:
        if s in done:
            continue
        db_path = os.path.join(workdir, f"bucket_{s:04d}.sqlite")
        info = BucketRunInfo()
        cnt = 0
        try:
            for t in iter_targets_seeded_connected_sqlite(
                    un, s, BUDGET, db_path, ckpt_every=CKPT_EVERY,
                    run_id=run_id, state=state, info=info, limits=limits,
                    stop_check=lambda: os.path.exists(stop_path)):
                _process_target(t, state, index, ff, k)
                cnt += 1
        except BucketStopped:
            # STOP mid-bucket: checkpoint preserved, bucket NOT recorded
            # as done (it resumes from its SQLite checkpoint next run).
            print(f"shard {shard_idx}: STOP mid-bucket {s}; checkpoint "
                  f"preserved, bucket not recorded as done", flush=True)
            _write_atomic(ckpt_path, {"volume": VOLUME, "piece": piece,
                                      "shard": shard_idx, "done": done,
                                      "state": state, "run_id": run_id})
            return
        except SearchLimit as e:
            print(f"shard {shard_idx}: limit hit mid-bucket {s} ({e}); "
                  f"checkpoint preserved, bucket not recorded as done",
                  flush=True)
            _write_atomic(ckpt_path, {"volume": VOLUME, "piece": piece,
                                      "shard": shard_idx, "done": done,
                                      "state": state, "run_id": run_id})
            return
        if info.completed:
            # info.targets is the bucket TOTAL (fresh run, resumed run, or
            # already-complete database): on a resumed run the generator
            # only re-yields targets not yet processed, so cnt alone would
            # under-count the bucket
            cnt = info.targets
        done[s] = cnt
        state["per_min_id"] = {str(k): v for k, v in sorted(done.items())}
        _write_atomic(ckpt_path, {"volume": VOLUME, "piece": piece,
                                  "shard": shard_idx, "done": done,
                                  "state": state, "run_id": run_id})
        db_mb = (os.path.getsize(db_path) / 1e6
                 if os.path.exists(db_path) else 0)
        print(f"shard {shard_idx}: min-id {s} done ({cnt:,} targets, "
              f"cumulative {state['targets']:,}, db {db_path} "
              f"{db_mb:.0f} MB, {time.time()-t0:.0f}s)", flush=True)
        if os.path.exists(stop_path):
            print(f"shard {shard_idx}: STOP file present; exiting without "
                  f"result (checkpoint preserved)", flush=True)
            return
    state["status"] = "complete"
    state["elapsed_s"] = round(time.time() - t0, 1)
    state["peak_rss_mb"] = round(
        resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024, 1)
    _write_atomic(result_path, state)
    os.remove(ckpt_path)
    print(f"shard {shard_idx}: COMPLETE {state['targets']:,} targets "
          f"({state['elapsed_s']}s, peak {state['peak_rss_mb']} MiB)",
          flush=True)


def aggregate(piece, workdir, plan):
    """Aggregate completed shards into final.json (internal conservation)."""
    total = _new_state(VOLUME, piece)
    total["workdir"] = workdir
    missing = []
    per_min_sum = 0
    for sh in plan["shards"]:
        path = os.path.join(workdir, f"shard_{sh['shard']:03d}.json")
        if not os.path.exists(path):
            missing.append(sh["shard"])
            continue
        with open(path) as f:
            r = json.load(f)
        total["targets"] += r["targets"]
        for key, v in r["funnel"].items():
            total["funnel"][key] += v
        total["sat"] += r["sat"]
        total["unsat"] += r["unsat"]
        total["covers_total"] += r.get("covers_total", 0)
        total["covers_max"] = max(total["covers_max"],
                                  r.get("covers_max", 0))
        total["witnesses"].extend(r["witnesses"])
        total["elapsed_s"] = max(total.get("elapsed_s", 0),
                                 r.get("elapsed_s", 0))
        total["peak_rss_mb"] = max(total.get("peak_rss_mb", 0),
                                   r.get("peak_rss_mb", 0))
        per_min_sum += sum(int(v) for v in r.get("per_min_id", {}).values())
    if missing:
        return None, missing
    # internal conservation: shard totals == per-min-id totals.  There is
    # NO expected total: the V45 total is unknown until this run completes.
    assert total["targets"] == per_min_sum, \
        (total["targets"], per_min_sum)
    _check_t_anchor(VOLUME, piece, total)  # no-op for V45 (no anchor)
    final = _finalize(VOLUME, piece, total, "COMPLETE")
    _write_atomic(os.path.join(workdir, "final.json"), final)
    _append_jsonl(final)
    return final, []


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--piece", required=True,
                    choices=sorted(PENTACUBES))
    ap.add_argument("--volume", type=int, default=VOLUME)
    ap.add_argument("--shard", type=int, default=None,
                    help="run one shard only (worker mode)")
    ap.add_argument("--parallel", type=int, default=2,
                    help="parallel workers (default 2; SQLite visited "
                         "sets bound per-worker RSS, so parallelism is "
                         "safe by construction)")
    ap.add_argument("--max-retries", type=int, default=5,
                    help="orchestrator re-launch attempts per shard")
    ap.add_argument("--max-seconds", type=float, default=None,
                    help="safety cap per bucket (checkpointed at the cap; "
                         "the bucket resumes on re-launch).  If a bucket "
                         "keeps exceeding it the shard aborts after "
                         "--max-retries")
    ap.add_argument("--prune-dbs", action="store_true",
                    help="delete COMPLETE bucket SQLite databases in the "
                         "workdir (audit evidence is preserved until this "
                         "explicit cleanup runs); incomplete databases are "
                         "never touched")
    args = ap.parse_args()

    assert args.volume == VOLUME, f"volume must be {VOLUME}"
    with open(PLAN_PATH) as f:
        plan = json.load(f)
    un = build_universe(VOLUME)
    startup_assertions(plan, un)
    workdir = combo_workdir(VOLUME, args.piece)
    os.makedirs(workdir, exist_ok=True)
    stop_path = os.path.join(workdir, "STOP")

    if args.prune_dbs:
        prune_completed_dbs(workdir)
        return 0

    if args.shard is not None:
        run_shard(args.piece, args.shard, plan, workdir, stop_path,
                  max_seconds=args.max_seconds)
        return

    final_path = os.path.join(workdir, "final.json")
    if os.path.exists(final_path):
        with open(final_path) as f:
            print(f"[prod] V45 {args.piece}: already complete (resume)")
        return
    pending = [s["shard"] for s in plan["shards"]
               if not os.path.exists(os.path.join(
                   workdir, f"shard_{s['shard']:03d}.json"))]
    print(f"[prod] V45 {args.piece}: {len(pending)} shards to run on "
          f"{args.parallel} workers (workdir {workdir})", flush=True)
    # Register the orchestrator itself so a crashed OpenWork session can
    # be detected as an orphaned launcher (see orphan_check.py).
    register_job(pid=os.getpid(), ppid=os.getppid(),
                 cmd=" ".join([sys.executable, os.path.abspath(__file__),
                               "--piece", args.piece]),
                 done_file=final_path, workdir=workdir)
    retries = {}
    queue = list(pending)
    running = {}
    while queue or running:
        while queue and len(running) < args.parallel:
            i = queue.pop(0)
            logf = open(os.path.join(workdir, f"shard_{i:03d}.log"), "a")
            cmd = [sys.executable, os.path.abspath(__file__),
                   "--piece", args.piece, "--shard", str(i)]
            if args.max_seconds is not None:
                cmd += ["--max-seconds", str(args.max_seconds)]
            p = subprocess.Popen(cmd, stdout=logf, stderr=subprocess.STDOUT)
            running[i] = p
            register_job(pid=p.pid, ppid=os.getpid(), cmd=" ".join(cmd),
                         done_file=os.path.join(
                             workdir, f"shard_{i:03d}.json"),
                         workdir=workdir)
            print(f"[prod] launched shard {i} (pid {p.pid})", flush=True)
        for i in [i for i, p in running.items() if p.poll() is not None]:
            rc = running.pop(i).returncode
            done = os.path.exists(os.path.join(
                workdir, f"shard_{i:03d}.json"))
            print(f"[prod] shard {i} finished rc={rc} "
                  f"result={'present' if done else 'absent'}", flush=True)
            if not done:
                retries[i] = retries.get(i, 0) + 1
                if retries[i] > args.max_retries:
                    raise RuntimeError(
                        f"shard {i} failed {args.max_retries} times; "
                        f"aborting (checkpoint preserved)")
                queue.append(i)  # re-launch (resumes from checkpoint)
        if os.path.exists(stop_path) and not queue:
            print("[prod] STOP file present; no shards in flight",
                  flush=True)
            break
        time.sleep(2)
    final, missing = aggregate(args.piece, workdir, plan)
    if final is None:
        print(f"[prod] incomplete: {len(missing)} shards missing "
              f"({missing}); re-run to resume", flush=True)
        return 1
    print(f"[prod] V45 {args.piece}: targets={final['number_of_targets']:,} "
          f"candidates={final['exact_cover_candidates']} "
          f"SAT={final['sat_count']} "
          f"(shard max {final['elapsed_shard_max_s']:.0f}s)", flush=True)
    print(f"[prod] final.json written to {final_path}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())