"""
Polycube symmetry primitives (cubic point group O_h, Lunnon classes).

Shared by the oddity-search work stream; nothing here mutates existing
solver code.  Conventions match the rest of the repo:

- A polycube is a finite set of integer cells (x, y, z); cubes join
  face-to-face (Manhattan distance 1).
- The 24 proper rotations are common.rotmatrix.RM.  The full achiral
  octahedral group O_h (48 elements) is RM combined with an optional
  global sign flip, stored as integer signed permutation matrices.
- normalize() shifts a cell set so its minimum coordinate is (0,0,0)
  and sorts it: the repo-wide canonical-cell-set convention (see
  solvers/reduce_solutions.py apply_transform_and_normalize).
- Symmetry classes are identified by W. F. Lunnon's codes (Lunnon 1972;
  reproduced with examples at https://sicherman.net/csym/).  The nine
  order-4 classes are identified structurally here from the matrix
  signature of the group:

      A12   cyclic, generated by a proper 4-fold rotation (C4)
      J10   cyclic, generated by an improper 4-fold rotation (S4)
      BB10  {c2_ortho x3}
      BC10  {c2_ortho, c2_diag, c2_diag}
      CE3   {c2_diag, mirror_diag, mirror_ortho}
      BF6   {c2_ortho, mirror_diag, mirror_diag}
      EE4   {c2_ortho, mirror_ortho, mirror_ortho}
      BE4   {c2_ortho, inversion, mirror_ortho}
      CK6   {c2_diag, inversion, mirror_diag}

  CK6 = <C, K> with C the 180-degree rotation about a face diagonal and
  K = inversion; the product C*K is the perpendicular plane-diagonal
  mirror.  (Verified against Sicherman's pages; see
  docs/frontier/ck6_oddity_design.md.)
"""

import numpy as np

from common.rotmatrix import RM

__all__ = [
    "OH_MATRICES",
    "PROPER_KEYS",
    "normalize",
    "canonical_form",
    "full_symmetry",
    "affine_symmetries",
    "element_kind",
    "order4_lunnon_code",
    "symmetry_order",
    "ck6_fixed_point_types",
    "ck6_affine_maps",
    "cell_orbits",
]


def _key(m):
    return tuple(tuple(int(v) for v in row) for row in m)


_PROPER_KEYS = {_key(np.asarray(r, dtype=int)) for r in RM}

# The 48 elements of O_h: proper rotations x optional inversion.
OH_MATRICES = [np.asarray(r * s, dtype=int) for r in RM for s in (1, -1)]
assert len({_key(m) for m in OH_MATRICES}) == 48

PROPER_KEYS = frozenset(_PROPER_KEYS)

_EYE = np.eye(3, dtype=int)


def normalize(cells):
    """Repo-convention canonical cell set: translate min to origin, sort."""
    cells = list(cells)
    mn = tuple(min(c[i] for c in cells) for i in range(3))
    return tuple(sorted(tuple(int(c[i] - mn[i]) for i in range(3)) for c in cells))


def canonical_form(cells, proper_only=False):
    """Lexicographically smallest normalized image over O_h (or rotations)."""
    mats = (m for m in OH_MATRICES
            if not proper_only or _key(m) in PROPER_KEYS)
    return min(normalize(tuple(m @ np.array(c) for c in cells)) for m in mats)


def full_symmetry(cells):
    """Point group of a cell set: all M in O_h with M*cells ~= cells.

    Congruence is up to translation (matrices only; the fixed point is
    the centroid).  Use affine_symmetries() when the translation matters.
    """
    base = normalize(cells)
    return [m for m in OH_MATRICES
            if normalize(tuple(m @ np.array(c) for c in cells)) == base]


def affine_symmetries(cells):
    """All (M, t) with integer t such that {M*v + t} == set(cells)."""
    cells = frozenset(tuple(int(v) for v in c) for c in cells)
    out = []
    for m in OH_MATRICES:
        img = [tuple(m @ np.array(c)) for c in cells]
        mn_img = tuple(min(c[i] for c in img) for i in range(3))
        mn_set = tuple(min(c[i] for c in cells) for i in range(3))
        t = tuple(mn_set[i] - mn_img[i] for i in range(3))
        moved = frozenset(tuple(c[i] + t[i] for i in range(3)) for c in img)
        if moved == cells:
            out.append((m, t))
    return out


def element_kind(m):
    """Structural kind of one O_h element (string)."""
    m = np.asarray(m, dtype=int)
    if np.array_equal(m, _EYE):
        return "identity"
    det = int(round(np.linalg.det(m)))
    tr = int(round(np.trace(m)))
    if np.array_equal(m, -_EYE):
        return "inversion"
    off_diag = any(m[i][j] != 0 for i in range(3) for j in range(3) if i != j)
    if det == 1:
        if tr == -1:
            # 180-degree rotation: axis is a coordinate axis (diagonal
            # matrix) or a face diagonal (off-diagonal nonzeros).
            return "c2_ortho" if not off_diag else "c2_diag"
        if tr == 1:
            return "c4"
        if tr == 0:
            return "c3"
    if det == -1:
        if tr == 1:
            return "mirror_ortho" if not off_diag else "mirror_diag"
        if tr == -3:
            return "inversion"  # unreachable (handled above), kept for safety
        if tr == -1:
            return "s4"
        if tr == 0:
            return "s6"
    return "other"


_ORDER4_V4_TABLE = {
    # sorted multiset of nontrivial element kinds -> Lunnon code
    ("c2_ortho", "c2_ortho", "c2_ortho"): "BB10",
    ("c2_diag", "c2_diag", "c2_ortho"): "BC10",
    ("c2_diag", "mirror_diag", "mirror_ortho"): "CE3",
    ("c2_ortho", "mirror_diag", "mirror_diag"): "BF6",
    ("c2_ortho", "mirror_ortho", "mirror_ortho"): "EE4",
    ("c2_ortho", "inversion", "mirror_ortho"): "BE4",
    ("c2_diag", "inversion", "mirror_diag"): "CK6",
}


def symmetry_order(syms):
    """|G| from an explicit element list."""
    return len(set(_key(m) for m in syms))


def order4_lunnon_code(syms):
    """Lunnon code of an order-4 group given its 4 matrices, else None.

    The nine order-4 polycube classes are A12, J10 (cyclic) and the
    seven Klein four-groups in _ORDER4_V4_TABLE.
    """
    syms = list(syms)
    if symmetry_order(syms) != 4:
        return None
    kinds = sorted(element_kind(m) for m in syms if element_kind(m) != "identity")
    if len(kinds) != 3:
        return None
    if any(k in ("c4", "s4") for k in kinds):
        # cyclic C4: proper generator -> A12, improper generator -> J10
        gens = [m for m in syms if element_kind(m) in ("c4", "s4")]
        return "A12" if any(_key(g) in PROPER_KEYS for g in gens) else "J10"
    return _ORDER4_V4_TABLE.get(tuple(kinds))


def ck6_fixed_point_types():
    """The four lattice placement types of CK6.

    With the C2 axis along the face diagonal (1,1,0), the group's fixed
    point is f = (a, a, b) with a, b in {0, 1/2}.  f == (0, 0, 0) (mod
    Z^3) is the only type with any K-fixed cell, hence the only type
    that can carry an odd-volume figure.
    """
    return ((0, 0), (0, 0.5), (0.5, 0), (0.5, 0.5))


def ck6_affine_maps(fixed_point):
    """The four CK6 affine maps for a fixed point f = (a, a, b).

    fixed_point is an (a, b) pair from ck6_fixed_point_types().  Returns
    a dict of callables acting on integer cells.  Closure on Z^3 is
    asserted on a sample window; a ValueError is raised for fixed
    points that do not act integrally.
    """
    a, b = fixed_point
    two_a, two_b = int(round(2 * a)), int(round(2 * b))

    def c_map(v):
        x, y, z = v
        return (y, x, two_b - z)

    def k_map(v):
        x, y, z = v
        return (two_a - x, two_a - y, two_b - z)

    maps = {
        "E": lambda v: v,
        "C": c_map,
        "K": k_map,
        "CK": lambda v: k_map(c_map(v)),
    }

    # integrality and pointwise distinctness on a sample window (the
    # window spans Z^3 affinely, so pointwise equality there is
    # equality of affine maps); then set-wise closure
    sample = [(x, y, z) for x in range(-2, 3)
              for y in range(-2, 3) for z in range(-2, 3)]
    if not all(all(coord == int(coord) for coord in m(v))
               for m in maps.values() for v in sample):
        raise ValueError(f"CK6 maps not integral for fixed point {fixed_point}")
    sigs = {tuple(m(v) for v in sample) for m in maps.values()}
    if len(sigs) != 4:
        raise ValueError(f"CK6 maps not distinct for fixed point {fixed_point}")
    for m1 in maps.values():
        for m2 in maps.values():
            for v in sample:
                comp = m1(m2(v))
                if not any(all(comp[i] == m(v)[i] for i in range(3))
                           for m in maps.values()):
                    raise ValueError(
                        f"CK6 maps not closed for fixed point {fixed_point}")

    return {name: (lambda vv, _m=m: tuple(int(c) for c in _m(vv)))
            for name, m in maps.items()}


def cell_orbits(cells, maps):
    """Orbits of the affine maps on the given cells (list of frozensets)."""
    cells = list(cells)
    seen, orbits = set(), []
    for v in cells:
        if v in seen:
            continue
        o = frozenset(m(v) for m in maps)
        orbits.append(o)
        seen |= o
    return orbits
