#!/usr/bin/env python3
"""
Package the verified EE4 5-R witness for George Sicherman.

Generates, from tests/fixtures/ee4_R_5.json only (no search code):

  reports/ee4_R_5_witness_description.md
      clean human-readable description: symmetry, R piece, the five
      placements (RM index, rotation as an axis permutation, translation,
      placed cells), the 25-cell target with z-slices, verification notes.

  reports/ee4_R_5_witness.png
      two-panel render: the R pentacube in canonical orientation, and the
      witness with the five pieces in distinct (colourblind-safe) colours.

Usage: python3 tools/package_ee4_R_george.py
"""

import json
import os
import sys

import numpy as np

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from common.rotmatrix import RM
from common.registry import PENTACUBES
from common.symmetry import normalize

FIXTURE = os.path.join(REPO_ROOT, "tests", "fixtures", "ee4_R_5.json")
OUT_DESC = os.path.join(REPO_ROOT, "reports", "ee4_R_5_witness_description.md")
OUT_PNG = os.path.join(REPO_ROOT, "reports", "ee4_R_5_witness.png")

# Okabe-Ito colourblind-safe palette
PIECE_COLOURS = ["#0072B2", "#D55E00", "#009E73", "#CC79A7", "#E69F00"]
R_PIECE_COLOUR = "#56B4E9"


def axis_permutation(M):
    """Describe a 3x3 matrix as (x,y,z) -> (..., ..., ...)."""
    terms = []
    for row in M:
        parts = []
        for j, v in enumerate(row):
            v = int(v)
            if v == 0:
                continue
            parts.append(("-" if v < 0 else "") + "xyz"[j])
        terms.append("".join(parts) if parts else "0")
    return "(" + ", ".join(terms) + ")"


def fmt_cells(cells):
    return " ".join(f"({x},{y},{z})"
                    for x, y, z in sorted(tuple(int(v) for v in c) for c in cells))


def fmt_matrix(m):
    return "[" + " ".join(
        "[" + ",".join(str(int(v)) for v in row) + "]" for row in m) + "]"


def build_description(fx):
    R = {tuple(int(v) for v in c) for c in PENTACUBES[fx["piece"]]}
    lines = []
    a = lines.append

    a("# EE4 5-R witness — description")
    a("")
    a(f"*Piece:* {fx['piece']} pentacube · *Symmetry class:* "
      f"{fx['symmetry_class']} · *Volume:* 25 cells · *Box:* "
      f"{fx['box']['min']}..{fx['box']['max']}")
    a("")
    a(f"*Symmetry:* {fx['symmetry_description']}.")
    a("")
    a("## The R pentacube")
    a("")
    a("Canonical coordinates (as in `common/registry.py`):")
    a("")
    a("```text")
    a("R = " + fmt_cells(R))
    a("```")
    a("")
    a("Only the 24 proper rotations are used; reflections are forbidden.")
    a("")
    a("## The five placements")
    a("")
    a("Each placement is `rotation RM[k]` applied to R, then translated by "
      "`t`.  The rotation is also written as an axis permutation "
      "`(x,y,z) -> (...)`.")
    a("")
    a("| piece | RM | rotation (x,y,z) -> | translation t | placed cells |")
    a("|---|---|---|---|---|")
    for i, pl in enumerate(fx["placements"]):
        k = pl["rotation_index"]
        t = tuple(pl["translation"])
        perm = axis_permutation(RM[k])
        cells = " ".join(f"({x},{y},{z})" for x, y, z in pl["cells"])
        a(f"| R{i} | RM[{k}] | `{perm}` | {t} | `{cells}` |")
    a("")
    a("All five rotations are proper (determinant +1).  The five pieces are "
      "pairwise disjoint and cover the target exactly.")
    a("")
    a("## The target (25 cells)")
    a("")
    a("Raw coordinates:")
    a("")
    a("```text")
    a(fmt_cells({tuple(c) for c in fx["target"]}))
    a("```")
    a("")
    a(f"Bounding box: `{fx['bbox']}`.")
    a("")
    a("Layer by layer, z from top to bottom:")
    a("")
    a("```text")
    for z in sorted({c[2] for c in fx["target"]}, reverse=True):
        layer = sorted(c for c in fx["target"] if c[2] == z)
        a(f"z={z}: " + fmt_cells(layer))
    a("```")
    a("")
    a("## Verification")
    a("")
    a("- 25 cells, face-connected;")
    a("- exact EE4 symmetry: order 4, kinds `c2_ortho, mirror_ortho, "
      "mirror_ortho`;")
    a("- five proper-rotation R placements, pairwise disjoint, exact cover;")
    a("- canonical form stable (matches `tests/fixtures/ee4_R_5.json`);")
    a("- independent verifier `tools/verify_ee4_R_witness.py`: "
      "ALL CHECKS PASSED;")
    a("- exhaustive search context: 16 tilings, 4 canonical targets "
      "(one shape under O_h), 119,023 nodes.")
    a("")
    a("*Generated by `tools/package_ee4_R_george.py` from "
      "`tests/fixtures/ee4_R_5.json`.*")
    return "\n".join(lines)


def render(fx):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Patch

    R = {tuple(int(v) for v in c) for c in PENTACUBES[fx["piece"]]}
    target = {tuple(c) for c in fx["target"]}
    colour_of = {}
    for i, pl in enumerate(fx["placements"]):
        for c in pl["cells"]:
            colour_of[tuple(c)] = PIECE_COLOURS[i]

    def draw(ax, cells, colour_map, title):
        xs = [c[0] for c in cells]
        ys = [c[1] for c in cells]
        zs = [c[2] for c in cells]
        ox, oy, oz = min(xs) - 1, min(ys) - 1, min(zs) - 1
        shape = (max(xs) - ox + 2, max(ys) - oy + 2, max(zs) - oz + 2)
        filled = np.zeros(shape, dtype=bool)
        fc = np.zeros(shape + (4,))
        for c in cells:
            x, y, z = c[0] - ox, c[1] - oy, c[2] - oz
            filled[x, y, z] = True
            fc[x, y, z] = matplotlib.colors.to_rgba(colour_map[c])
        ax.voxels(filled, facecolors=fc, edgecolors="#1a1a1a", linewidth=0.5)
        ax.set_box_aspect(shape)
        ax.view_init(elev=22, azim=-55)
        ax.set_axis_off()
        ax.set_title(title, fontsize=11, pad=2)

    fig = plt.figure(figsize=(11.5, 5.6))
    ax1 = fig.add_subplot(1, 2, 1, projection="3d")
    draw(ax1, R, {c: R_PIECE_COLOUR for c in R},
         "The R pentacube (canonical orientation)")
    ax2 = fig.add_subplot(1, 2, 2, projection="3d")
    draw(ax2, target, colour_of,
         "EE4 5-R witness (25 cells, five pieces)")

    legend_items = [Patch(facecolor=PIECE_COLOURS[i], edgecolor="#1a1a1a",
                          label=f"R{i}: RM[{fx['placements'][i]['rotation_index']}]"
                                f" + {tuple(fx['placements'][i]['translation'])}")
                    for i in range(5)]
    fig.legend(handles=legend_items, loc="lower center", ncol=5,
               fontsize=8.5, frameon=False, bbox_to_anchor=(0.5, 0.02))
    fig.suptitle("EE4 5-R construction — dual orthogonal mirror symmetry "
                 "(mirrors x=0, y=0)", fontsize=12, y=0.98)
    fig.tight_layout(rect=(0, 0.06, 1, 0.95))
    fig.savefig(OUT_PNG, dpi=160, facecolor="white")
    plt.close(fig)


def main():
    with open(FIXTURE) as f:
        fx = json.load(f)

    desc = build_description(fx)
    with open(OUT_DESC, "w") as f:
        f.write(desc)
    print("->", OUT_DESC)

    render(fx)
    print("->", OUT_PNG)


if __name__ == "__main__":
    main()