#!/usr/bin/env python3
"""
Verify the smallest known odd box of every pentacube catalogue against
George Sicherman's "Pentacubes in an Odd Box" page.

Reference: https://sicherman.net/c5box/c5oddbox.html

Method
------
For every catalogue in catalogues/*_catalogue.py we collect every box the
catalogue marks as tileable:

  * RAW_PRIMES / catalogue.primes
  * PUBLISHED_SOLUTIONS / catalogue.published_solutions
  * ROW_FAMILIES (period families, plus semigroup sums when no period is set)

and pick the smallest *odd* box (all three dimensions odd), ranked by

  tile count (volume / 5), then volume, then lexicographic dimensions.

Boxes that are impossible (catalogue.impossible_reason), boxes that were
searched with no solution, and boxes whose volume is not a multiple of 5 are
ignored. Composite status is ignored: any box the catalogue asserts as
tileable counts. Width splits are decomposition rules rather than tileability
claims, and any odd box derived from them would be beaten by a strictly
smaller odd box from its own parts, so they cannot affect the minimum.

The result is compared against Sicherman's published minimum (hard-coded
below). Pieces that have no catalogue file in the repo (G, I, X) are reported
as SKIP and are not counted in the summary.

This script is read-only: it never modifies catalogue files.
"""

import glob
import importlib
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from catalogues.base import Box  # noqa: E402

# ---------------------------------------------------------------------------
# George Sicherman, "Pentacubes in an Odd Box"
# https://sicherman.net/c5box/c5oddbox.html
#
# "none"       -> no smallest odd box is known
# "impossible" -> the piece cannot tile any odd box
# otherwise    -> (a, b, c) smallest known odd box
# ---------------------------------------------------------------------------
SICHERMAN = {
    "A": "none",
    "B": (3, 13, 15),
    "E": (5, 5, 5),
    "F": (5, 5, 11),
    "G": "impossible",
    "H": (5, 5, 9),
    "I": (1, 1, 5),
    "J": (3, 5, 5),
    "K": (3, 5, 9),
    "L": (3, 5, 5),
    "M": "impossible",
    "N": (5, 5, 5),
    "P": (3, 3, 5),
    "Q": (5, 5, 9),
    "R": (5, 7, 19),
    "S": (5, 9, 15),
    "T": (3, 15, 17),
    "U": (3, 5, 7),
    "V": (5, 5, 9),
    "W": (5, 7, 9),
    "X": "impossible",
    "Y": (5, 5, 5),
    "Z": (5, 9, 15),
}

# Cap for lengths generated from row families. Every odd length generated by
# the families in the catalogues lies far below this bound, so the cap can
# never hide a smaller odd box.
FAMILY_LENGTH_CAP = 1000


def fmt_box(box):
    return f"({box.a},{box.b},{box.c})"


def family_lengths(family):
    """Lengths claimed tileable by a row family (capped).

    With a period, the lengths are seed + k*period for k >= 0. Without a
    period, the seeds are treated as semigroup generators.
    """
    seeds = list(family.seeds)
    if not seeds:
        return set()

    lengths = set()
    if family.period is not None and family.period > 0:
        p = family.period
        max_k = (FAMILY_LENGTH_CAP - min(seeds)) // p + 1
        for s in seeds:
            for k in range(max_k + 1):
                c = s + k * p
                if c <= FAMILY_LENGTH_CAP:
                    lengths.add(c)
    else:
        # Semigroup closure of the seeds.
        lengths = set(seeds)
        frontier = set(seeds)
        while frontier:
            nxt = set()
            for a in frontier:
                for s in seeds:
                    total = a + s
                    if total <= FAMILY_LENGTH_CAP and total not in lengths:
                        lengths.add(total)
                        nxt.add(total)
            frontier = nxt
    return lengths


def collect_candidates(module, catalogue):
    """Every box the catalogue asserts tileable, as {Box: source labels}."""
    candidates = {}

    def add(box, source):
        key = box.canonical()
        candidates.setdefault(key, set()).add(source)

    raw_primes = set(getattr(module, "RAW_PRIMES", set()) or set())
    inst_primes = set(getattr(catalogue, "primes", set()) or set())
    for box in raw_primes | inst_primes:
        add(box, "RAW_PRIMES")

    raw_pub = set(getattr(module, "PUBLISHED_SOLUTIONS", set()) or set())
    inst_pub = set(getattr(catalogue, "published_solutions", set()) or set())
    for box in raw_pub | inst_pub:
        add(box, "published_solutions")

    families = getattr(catalogue, "row_families", {}) or {}
    for (a, b), family in families.items():
        for c in family_lengths(family):
            add(Box(a, b, c), "row_families")

    return candidates


def collect_searched_no_solution(module, catalogue):
    """Boxes the catalogue says were searched with no solution."""
    rejected = set()
    for box in getattr(module, "SEARCHED_NO_SOLUTION", set()) or set():
        rejected.add(box.canonical())
    for box in getattr(catalogue, "searched_no_solution", set()) or set():
        rejected.add(box.canonical())
    return rejected


def odd_candidates(module, catalogue):
    """Odd, known-tileable boxes, ranked by (tile count, volume, dims)."""
    rejected = collect_searched_no_solution(module, catalogue)
    candidates = collect_candidates(module, catalogue)

    ranked = []
    for box, sources in candidates.items():
        if not (box.a % 2 == 1 and box.b % 2 == 1 and box.c % 2 == 1):
            continue  # not an odd box
        volume = box.a * box.b * box.c
        if volume % 5 != 0:
            continue  # cannot be tiled by pentacubes
        if box in rejected:
            continue  # searched with no solution
        try:
            if catalogue.impossible_reason(box) is not None:
                continue  # marked impossible
        except Exception:
            pass  # never let a broken rule hide a candidate
        ranked.append((box, sources))

    ranked.sort(
        key=lambda t: (
            t[0].a * t[0].b * t[0].c // 5,  # tile count
            t[0].a * t[0].b * t[0].c,       # volume
            (t[0].a, t[0].b, t[0].c),       # lexicographic dimensions
        )
    )
    return ranked


def compare(computed, expected):
    """True when the catalogue minimum agrees with Sicherman."""
    if computed is None:
        return isinstance(expected, str)  # "none" or "impossible"
    if isinstance(expected, tuple):
        return computed == Box(*expected).canonical()
    return False


def explain(ranked, expected, computed):
    """Which catalogue entries caused a mismatch."""
    lines = []
    if computed is None:
        lines.append("      note: no odd tileable box in the catalogue data")
    else:
        v = computed.a * computed.b * computed.c
        if isinstance(expected, tuple):
            exp = Box(*expected).canonical()
            exp_vol = exp.a * exp.b * exp.c
            if v < exp_vol:
                lines.append(
                    "      note: catalogue data claims an odd box smaller than "
                    "Sicherman's minimum"
                )
            elif v > exp_vol:
                lines.append(
                    "      note: catalogue's smallest odd box is larger than "
                    "Sicherman's minimum"
                )
        shown = ranked[:6]
        parts = [f"{fmt_box(b)} [{','.join(sorted(s))}]" for b, s in shown]
        if len(ranked) > len(shown):
            parts.append(f"... and {len(ranked) - len(shown)} more")
        lines.append("      note: odd candidates: " + ", ".join(parts))

    if isinstance(expected, tuple):
        exp = Box(*expected).canonical()
        if not any(b == exp for b, _ in ranked):
            lines.append(
                f"      note: Sicherman box {fmt_box(exp)} is not in the catalogue data"
            )
    return "\n".join(lines)


def main():
    repo_catalogues = {}
    pattern = os.path.join(REPO_ROOT, "catalogues", "*_catalogue.py")
    for path in sorted(glob.glob(pattern)):
        stem = os.path.splitext(os.path.basename(path))[0]
        name = stem.split("_")[0].upper()
        repo_catalogues[name] = path

    print("# Sicherman 'Pentacubes in an Odd Box' verification")
    print("# Reference: https://sicherman.net/c5box/c5oddbox.html")
    print()

    matches = 0
    mismatches = 0

    for name in SICHERMAN:
        if name not in repo_catalogues:
            expected = SICHERMAN[name]
            label = expected if isinstance(expected, str) else fmt_box(Box(*expected))
            print(f"SKIP  {name}  no catalogue in repo (Sicherman: {label})")
            print()
            continue

        try:
            module = importlib.import_module(f"catalogues.{name.lower()}_catalogue")
            catalogue = getattr(module, f"{name}_CATALOGUE")
            ranked = odd_candidates(module, catalogue)
        except Exception as exc:  # a broken catalogue must not kill the run
            print(f"ERROR {name}  failed to load catalogue: {exc}")
            print()
            continue

        computed = ranked[0][0] if ranked else None
        expected = SICHERMAN[name]

        if compare(computed, expected):
            matches += 1
            if isinstance(expected, str):
                print(f"PASS  {name}  {expected}")
            else:
                print(
                    f"PASS  {name}  catalogue={fmt_box(computed)}  "
                    f"Sicherman={fmt_box(Box(*expected))}"
                )
        else:
            mismatches += 1
            print(f"FAIL  {name}")
            if computed is None:
                print("      catalogue=none")
            else:
                print(f"      catalogue={fmt_box(computed)}")
            if isinstance(expected, str):
                print(f"      Sicherman={expected}")
            else:
                print(f"      Sicherman={fmt_box(Box(*expected))}")
            print(explain(ranked, expected, computed))
        print()

    extra = sorted(set(repo_catalogues) - set(SICHERMAN))
    for name in extra:
        print(f"WARN  {name}  catalogue exists but has no Sicherman entry")
        print()

    missing = [k for k in SICHERMAN if k not in repo_catalogues]
    print("Summary:")
    print(f"Matches: {matches}")
    print(f"Mismatches: {mismatches}")
    if missing:
        print(f"Not compared (no catalogue in repo): {', '.join(missing)}")


if __name__ == "__main__":
    main()
